### ISSUE TITLE
U2F Authentication - seg violation / nil pointer deref

### ISSUE THREAD

**Issue by james-d-elliott** [clems4ever/authelia#426] opened 2019-11-02 22:48 UTC
Getting the following debug logs. I think it's only occurring with U2F keys. I was testing the master build (so this is for your information only) from docker hub on my k8s. It allows me to register a key, but then seems to crash when trying to authenticate.

time="2019-11-02T22:44:48Z" level=trace msg="Request hit" method=GET path=/api/state remote_ip=10.32.0.3
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa7c562]

goroutine 22 [running]:
github.com/clems4ever/authelia/middlewares.(*AutheliaCtx).Error(0x0, 0xe69e00, 0xc0002b1d80, 0xcd3f0a, 0x10)
        /go/src/app/middlewares/authelia_context.go:50 +0xc2
github.com/clems4ever/authelia/middlewares.AutheliaMiddleware.func1.1(0xc0003f0000)
        /go/src/app/middlewares/authelia_context.go:40 +0x15f
github.com/fasthttp/router.(*Router).Handler(0xc0003660a0, 0xc0003f0000)
        /go/pkg/mod/github.com/fasthttp/router@v0.5.2/router.go:326 +0xfb3
github.com/clems4ever/authelia/middlewares.LogRequestMiddleware.func1(0xc0003f0000)
        /go/src/app/middlewares/log_request.go:14 +0xa2
github.com/valyala/fasthttp.(*Server).serveConn(0xc0003ca400, 0xe7ee80, 0xc0000a8208, 0x0, 0x0)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/server.go:2018 +0x6ab
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0003aa8c0, 0xc0002c8aa0)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/workerpool.go:223 +0xc0
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc0003aa8c0, 0xc0002c8aa0, 0xba75a0, 0xc0002c8aa0)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/workerpool.go:195 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
        /go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/workerpool.go:194 +0x101

**Comment by clems4ever** [comment] 2019-11-03 09:18
Hello @james-d-elliott , thank you for notifiying about this bug. I will try to reproduce today.

**Comment by james-d-elliott** [comment] 2019-11-03 21:14
No worries, thanks for the awesome product.

Let me know if there is anything I can do, I am running 3.16.2 right now but can just edit my config for 4 anytime and run it on a second mongo db.

It shouldn't affect anything but I'm using traefik 1.7 ingress, everything works fine with the same config on 3.16.2 (except removing the jwt token).

**Comment by clems4ever** [comment] 2019-11-16 22:23
I've found the bug. I'm fixing it.

**Comment by Tedyst** [comment] 2019-11-17 11:02
I also found this bug while trying to setup U2F. I think that the problem here is that the type `elliptic.Curve` cannot be unmarshalled back from json. Maybe this is related to golang/go#33564 ?
Anyhow, this is the error that I get now using my fork:
```
ERRO[0079] Unable to retrieve user session: json: cannot unmarshal object into Go struct field PublicKey.U2FRegistration.PubKey.Curve of type elliptic.Curve  method=POST path=/api/secondfactor/u2f/sign remote_ip=127.0.0.1 stack="/media/hddext4/Git/authelia/middlewares/authelia_context.go:53             (*AutheliaCtx).Error
/media/hddext4/Git/authelia/middlewares/authelia_context.go:40             AutheliaMiddleware.func1.1
/home/tedy/go/pkg/mod/github.com/fasthttp/router@v0.5.2/router.go:326      (*Router).Handler
/media/hddext4/Git/authelia/middlewares/log_request.go:14                  LogRequestMiddleware.func1
/home/tedy/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/server.go:2018    (*Server).serveConn
/home/tedy/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/workerpool.go:223 (*workerPool).workerFunc
/home/tedy/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/workerpool.go:195 (*workerPool).getCh.func1
/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357                              goexit"
```

**Comment by clems4ever** [comment] 2019-11-17 14:25
Thanks for the PR. It seems to indeed fix 2 bugs. LGTM.

**Comment by clems4ever** [comment] 2019-11-18 23:11
Do you guys confirm that the issue is now solved at head?

**Comment by james-d-elliott** [comment] 2019-11-19 00:19
I'll have to setup the head version again, I'm at work currently will check in about 6 hours.

**Comment by Tedyst** [comment] 2019-11-19 04:08
I can confirm that this works for me. Thanks!

**Comment by clems4ever** [comment] 2019-11-19 07:49
Great! Thanks @Tedyst .
@james-d-elliott I'm closing the issue but don't hesitate to re-open it if you see any remaining problem.

**Closed by clems4ever** 2019-11-19 07:49 UTC
Labels: P1, bug
