### ISSUE TITLE
Unhandled rejection MongoNetworkError: failed to connect to server [mongo:27017] on first connect

### ISSUE THREAD

**Issue by ps-tfriedl** [clems4ever/authelia#249] opened 2018-08-12 16:17 UTC
I managed to get a working setup by following the example.

However as soon as I want to persist my mongo db, authelia fails with this error: Unhandled rejection MongoNetworkError: failed to connect to server [mongo:27017] on first connect

On first look it seems that authelia is too fast during the setup and persisting mongo delays it's startup.  I already put a depends_on for the mongo container.

#Working
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

#Not working
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./authelia/mongo/data:/data/db

**Comment by clems4ever** [comment] 2018-08-13 12:43
Hello @ps-tfriedl , can you confirm your hypothesis by starting mongo for few seconds and then Authelia and see if you still have the issue?

**Comment by ps-tfriedl** [comment] 2018-08-13 13:26
Confirmed. If I start mongo as a separate container (but in the same docker network) it works with a mounted volume. If it's in the same docker-compose file it breaks with "failed to connect to server".

**Comment by clems4ever** [comment] 2018-08-13 14:56
Did you know that you can do `docker-compose up -d mongo` to only start mongo even if both services are in the same docker-compose?

For the issue, I definitely need to implement some kind of retry mechanism, I'll have a look. thank you for the heads up.

**Comment by clems4ever** [comment] 2018-08-19 09:06
Well, I'm having a look since this is a serious issue regarding resiliency.

**Comment by clems4ever** [comment] 2018-08-19 14:46
#258  should address this issue.

**Comment by clems4ever** [comment] 2018-08-19 14:49
@jmccoy555 , I did not reproduce your use case.
However, when Authelia restarts and mongo is not reachable during the restart, then Authelia is broken once and for all even if mongo comes back up. This is what I fixed in this PR.

**Comment by ps-tfriedl** [comment] 2018-08-19 15:04
Thanks @clems4ever - much appreciated! And thanks for the tip - I did not know that I can start containers of a docker-compose file individually.

**Comment by jmccoy555** [comment] 2018-08-19 16:30
Hi @clems4ever I'm just pulling the latest image and will have a play. 

FYI - I'm running esxi with a Ubuntu Docker VM hosting Mongo and Redis and VIC hosting Authelia. Rebooting the Ubuntu VM caused the issue before. I'll see if this still happens and report back if so. 

Thanks!

**Comment by jmccoy555** [comment] 2018-08-19 17:16
@clems4ever Me again..... just quickly tried this, v3.8.0 that is.

It initially didn't work at all ( Authentication failed. Please check your credentials. ) but looking though the nginx example it looks like the /auth_verify has changed a bit. I updated one of my single auth method domains quickly and it worked again, well, I got past the first factor log in screen, however I got passed to the second factor screen. Obviously this shouldn't have happened. So I manually typed the original destination url and I was let in, so the second factor wasn't required.

Is there some other change in the config?? I can't see anything.

I've rolled back for now as updating my nginx config is going to take a bit of time.

**Comment by clems4ever** [comment] 2018-08-24 20:10
Hello @jmccoy555 , which version of Authelia were you using before so that I can check if there were other changes between the versions?

**Comment by jmccoy555** [comment] 2018-08-24 20:57
Hi @clems4ever v3.7.1 works perfectly (pulled from Docker Hub).

**Comment by clems4ever** [comment] 2018-08-25 17:29
I had a look at the diff between v3.7.1 and v3.8.0 and indeed, there is a breaking change in the nginx configuration. `redirect=` has been replaced by `rd=`. It has been changed for the nginx configuration to be compatible with Kubernetes ingress controller.

**Comment by clems4ever** [comment] 2018-08-25 17:35
I'm closing this issue since #258 has been merged to address the original problem. I let you open new issues for other problems if you still have some.

**Closed by clems4ever** 2018-08-25 17:35 UTC
Labels: P1, question

**Comment by jmccoy555** [comment] 2018-10-27 13:36
> 
> 
> @jmccoy555 , I did not reproduce your use case.
> However, when Authelia restarts and mongo is not reachable during the restart, then Authelia is broken once and for all even if mongo comes back up. This is what I fixed in this PR.

Hi @clems4ever, I've just updated to the latest build on Docker hub (v3.9.5 I think) and can confirm that the connection to Mongo now recovers in my environment unlike before!! :smiley:

**Comment by clems4ever** [comment] 2018-10-27 13:58
Good to know! Thanks!
