### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by ishioni** [clems4ever/authelia#455] opened 2019-11-25 15:32 UTC
The topic of a helm chart has been talked about for some time, I went ahead and did it. You can take a look here https://gitlab.com/inzmovi/helm-charts/tree/master/charts/authelia

However, I'm not about to PR it here, since

#1 It's for v3.16.2
I'm not interested in writing one for 4.0 yet, as it's in beta, but you don't have a stable branch to merge to. However, from what I can see, 4.0 would only incur minimal changes going forward (at least for now)

#2 It's not perfect yet, I'd like feedback
I especially don't like the way I handle a user file database. Secrets/configmaps are readonly in kubernetes, so it's impossible for a user to change his password. Yet it's unreasonably hard to calculate it beforehand. If the passwords for users were to be kept separate of that file, this problem would be fixed.

#3 I have some grievances about documentation
Automated tests are not documentation. It took a lot of trial&error on finding the right combination of annotations to display to the user once the chart is deployed. What's worse, some info on the Issue page on GH is flat out wrong (especially the one about traefik - it STILL needs a double redirect, and rightfully so). Nowhere is it plain out said that one should point at the internal service, and not the external (public) URL. Figuring out that authelia expects root access to mongodb was just icing on the cake. I'm sorry if this sounds negative, but the idea about helm charts is that the user needs make as little change to the default values (if any!) as necessary for the chart to work. I don't need to know how to run automated suite tests. I do need to know what env variables the application accepts, and what they do.

**Comment by clems4ever** [comment] 2019-11-25 20:04
Hello @ishioni,

First, thank you very much for your feedbacks.

Helm charts has indeed been discussed for a long time but nobody actually made a PR to introduce
it (even before v4 was started) even though some people from the community already created some charts. On my side, I had no time to integrate them and do the PR myself.

That's very good thing that you made it working for v3 and you solved your issues. It should not be very hard to change for v4 but I understand your reasons to not use the alpha version of v4. For your info, I'm doing the latest changes to simplify the UI before releasing the stable version of v4 (likely in a few days).
Also your issue is coming at the right moment because I had in mind to next work on the Helm chart for v4. If some pre-requisite changes must be done (and I know that there are many), I'm ready to do them or review PRs.

Regarding password management, as described in the documentation, using a file-based users database is the wrong way to go if you want a full-featured Authelia running. You should definitely use a LDAP server or an AD if you need an actually working solution in which you can update the passwords in a multi-node setup.
We can surely discuss how we could store users in DB if you don't want to handle a LDAP server but that is out of scope of this issue and definitely not a priority for me.

Regarding 3, I hear your complaints but bear with me and please help us improve the situation by proposing PRs solving the pain points that you faced. That would be a great way to contribute and I'd be happy to review your changes.
Also, the particular problem you faced with Traefik is likely due to the fact that Traefik evolves independently from Authelia and the example has not been created for Kubernetes anyway. Also I'm not an expert in Traefik configuration so, as I said, don't hesitate to contribute on the topic.

> but the idea about helm charts is that the user needs make as little change to the default values (if any!) as necessary for the chart to work

I completely agree. Let's work together and propose changes to be done for making Authelia configuration more user-friendly and adapted for Helm charts.

Don't hesitate to come and chat on the Gitter. I'd be more than happy to exchange ideas on how to improve the situation and discuss how we can work together.

Cheers!

**Comment by ishioni** [comment] 2019-11-25 21:36
> It should not be very hard to change for v4 but I understand your reasons to not use the alpha version of v4. For your info, I'm doing the latest changes to simplify the UI before releasing the stable version of v4 (likely in a few days).
> Also your issue is coming at the right moment because I had in mind to next work on the Helm chart for v4. If some pre-requisite changes must be done (and I know that there are many), I'm ready to do them or review PRs.

Just to be clear - I didn't have a specific issue ;) I would be more than happy to merge a chart for v3, but there isn't a branch for that. So if you'd fork to a branch lets say stable, that would work. No idea if you care however. As far as I understand, v4 is a moving target for now, so no reason to start modifying for it now, when things could change (for example I see you're exploring other DBs than mongo). Once you declare v4 as finished, I'll probably make a PR for that.

> Regarding password management, as described in the documentation, using a file-based users database is the wrong way to go if you want a full-featured Authelia running. You should definitely use a LDAP server or an AD if you need an actually working solution in which you can update the passwords in a multi-node setup.
> We can surely discuss how we could store users in DB if you don't want to handle a LDAP server but that is out of scope of this issue and definitely not a priority for me.

I can totally understand not wanting to support that. However, I think there's a valid usecase here. For me specifically, I have a miniature server for a couple of apps that I share with my family and friends. I could (and probably) should setup an LDAP infrastructure for them, but I honestly struggle to find one with a good-enough UI for self-service for example (like resetting passwords). phpldapadmin is old, ugly and not really maintained. However, if you would extend authelia to be a frontend for that, where it could manage users and groups, that would solve it for me. Then I could include it as a dependency in the chart, and just forgo any interest in maintaining the file backend. However, I understand that may be way out of scope. I do remember you talking about at least a LDAP password reset dialogue. Any comments on that?

> Regarding 3, I hear your complaints but bear with me and please help us improve the situation by proposing PRs solving the pain points that you faced. That would be a great way to contribute and I'd be happy to review your changes.

I disagree on this heavily. Whoever writes the code should document it. Do understand - I'm not asking for guides, eg "How to make authelia work with traefik". I do however ask for docs/configuration.md to explain more-or-less what each config option does. Same would go for a hypothetical docs/env_values.md

> Also, the particular problem you faced with Traefik is likely due to the fact that Traefik evolves independently from Authelia and the example has not been created for Kubernetes anyway. Also I'm not an expert in Traefik configuration so, as I said, don't hesitate to contribute on the topic.

Nginx is also not part of authelia, and in fact it's not documented head-on how to integrate it with authelia as well. Unless we count the tests. And yes, a docs/integration.md would be nice, and in fact could be written. But please note, this is different than the documentation I am asking for above.

Also, don't sell yourself short on traefik knowledge. I remember reading your comment on an issue about those redirects, and you explained - traefik doesn't do redirects, the app needs to. So we need 2 redirects - one in case the user is not logged in, and the second to the actual app.

> [..] 
> I completely agree. Let's work together and propose changes to be done for making Authelia configuration more user-friendly and adapted for Helm charts.

I think the right way to go about this is to define a clear goal on what the chart should and should not do. Do we care about development-like deployments? Where no DB/persistent storage/ldap is avaible? Or should we strive to only provide production-ready ones?

> Don't hesitate to come and chat on the Gitter. I'd be more than happy to exchange ideas on how to improve the situation and discuss how we can work together.

I just did, let's continue the discussion there

**Comment by leodotcloud** [comment] 2019-11-28 00:00
FYI, I had authored a chart some time back: https://github.com/rancher/charts/pull/93. Not sure if it's helpful in the current context. https://github.com/clems4ever/authelia/issues/311

**Comment by clems4ever** [comment] 2019-12-08 13:49
I'm closing this issue as it is a duplicate of #274.

**Closed by clems4ever** 2019-12-08 13:49 UTC
Labels: P3, enhancement
