### ISSUE TITLE
nginx config files

### ISSUE THREAD

**Issue by Iwan-Authelia** [clems4ever/authelia#466] opened 2019-11-30 05:42 UTC
Hi,

I've been testing with Authelia and have some issues getting the nginx config correct.

What I am trying to do is the following;

1. Hosting Authelia on a publicly accessible server
2. When 2FA is successful calling a proxy-pass to an internal webserver which hosts the actual website.

As there are multiple examples for nginx configs here I have tried all or at least most of them but so far I have been unable to get it all working.

I've attached a zip file with my configs (Authelia and nginx, anonymised)
in etc/nginx/sites-available/reverse-proxy.conf is a working config for a not-protected proxy-pass. The purpose is to protect this by Authelia.

[authelia-test-config.zip](https://github.com/clems4ever/authelia/files/3906766/authelia-test-config.zip)

I post it here for two reasons, first, I'm stuck and hope for some help :) Second, I hope to help others getting this up and running by sharing some working configs.

**Comment by nightah** [comment] 2019-11-30 10:30
I've included an extract of my nginx config below.

This includes, the Authelia application hosted in Docker as the container named `authelia` and published at `auth.example.com` an example of Nextcloud hosted in Docker as the container named `nextcloud` and published at `nextcloud.example.com` and the respective additional nginx configuration.

`authelia.conf` is included on every host as part of the template, however, I only include `auth.conf` for endpoints that need protection and have been configured in my Authelia `config.yml`. The `proxy.conf` is included whenever reverse proxying.

**auth.example.com**
```nginx
server {
    server_name auth.example.com;
    listen 80;
    return 301 https://$server_name$request_uri;
}

server {
    server_name auth.example.com;
    listen 443 ssl http2;
    include /config/nginx/ssl.conf;

    location / {
        set $upstream_authelia http://authelia:8080;
        proxy_pass $upstream_authelia;
        include /config/nginx/proxy.conf;
    }
}
```

**nextcloud.example.com**
```nginx
server {
    server_name nextcloud.example.com;
    listen 80;
    return 301 https://$server_name$request_uri;
}

server {
    server_name nextcloud.example.com;
    listen 443 ssl http2;
    include /config/nginx/ssl.conf;
    include /config/nginx/authelia.conf;

    location / {
        set $upstream_nextcloud https://nextcloud;
        proxy_pass $upstream_nextcloud;
        include /config/nginx/auth.conf;
        include /config/nginx/proxy.conf;
    }
}
```

**authelia.conf**
```nginx
location /authelia {
    internal;
    set $upstream_authelia http://authelia:8080/api/verify;
    proxy_pass_request_body off;
    proxy_pass $upstream_authelia;
    proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
    proxy_set_header Content-Length "";

    # Timeout if the real server is dead
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

    # Basic Proxy Config
    client_body_buffer_size 128k;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Uri $request_uri;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_redirect  http://  $scheme://;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_cache_bypass $cookie_session;
    proxy_no_cache $cookie_session;
    proxy_buffers 4 32k;

    # Advanced Proxy Config
    send_timeout 5m;
    proxy_read_timeout 240;
    proxy_send_timeout 240;
    proxy_connect_timeout 240;
}
```

**auth.conf**
```nginx
# Basic Authelia Config
auth_request /authelia;
auth_request_set $target_url $scheme://$http_host$request_uri;
auth_request_set $user $upstream_http_remote_user;
auth_request_set $groups $upstream_http_remote_groups;
proxy_set_header X-Forwarded-User $user;
proxy_set_header X-Forwarded-Groups $groups;
error_page 401 =302 https://auth.example.com/#/?rd=$target_url;
```

**proxy.conf**
```nginx
client_body_buffer_size 128k;

#Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

# Advanced Proxy Config
send_timeout 5m;
proxy_read_timeout 360;
proxy_send_timeout 360;
proxy_connect_timeout 360;

# Basic Proxy Config
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Ssl on;
proxy_redirect  http://  $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 64 256k;

# If behind reverse proxy, forwards the correct IP
set_real_ip_from 10.0.0.0/8;
set_real_ip_from 172.0.0.0/8;
set_real_ip_from 192.168.0.0/16;
set_real_ip_from fc00::/7;
real_ip_header X-Forwarded-For;
real_ip_recursive on;
```

**Comment by nightah** [comment] 2019-12-04 02:03
@Iwan-Authelia does this help, has your issue been resolved?

**Comment by Iwan-Authelia** [comment] 2019-12-04 13:37
@nightah Thanks mate, it helped a lot and I have a working setup. Still trying to resolve a few issues, I will post a follow up over the next few days. One of the issues is that emails sent to reset password or register a 2fa device have a none working link starting with https:/// instead of https://domain/
I'm using the V4 binary artifact posted by @clems4ever lately.

**Comment by nightah** [comment] 2019-12-04 23:19
@Iwan-Authelia this email template is a configuration issue on my side there was a missing header.

**proxy.conf**
```nginx
client_body_buffer_size 128k;

#Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

# Advanced Proxy Config
send_timeout 5m;
proxy_read_timeout 240;
proxy_send_timeout 240;
proxy_connect_timeout 240;

# Basic Proxy Config
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $http_host;
proxy_set_header X-Forwarded-Uri $request_uri;
proxy_set_header X-Forwarded-Ssl on;
proxy_redirect  http://  $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 4 32k;
#proxy_buffers 32 4k;

# If behind reverse proxy, forwards the correct IP
set_real_ip_from 10.0.0.0/8;
set_real_ip_from 172.0.0.0/8;
set_real_ip_from 192.168.0.0/16;
set_real_ip_from fc00::/7;
real_ip_header X-Forwarded-For;
real_ip_recursive on;
```

**Comment by Iwan-Authelia** [comment] 2019-12-05 01:17
@nightah That did the trick! Thanks!

**Comment by clems4ever** [comment] 2019-12-05 16:04
Can we close the thread if the issue is reolved? Thanks.

**Comment by clems4ever** [comment] 2019-12-05 16:08
I'm closing it, please reopen if needed.

**Closed by clems4ever** 2019-12-05 16:08 UTC

**Comment by nightah** [comment] 2019-12-17 22:54
@Iwan-Authelia also another small adjustments to make sure redirects work:

**auth.conf**
```nginx
# Basic Authelia Config
auth_request /authelia;
auth_request_set $target_url $scheme://$http_host$request_uri;
auth_request_set $user $upstream_http_remote_user;
auth_request_set $groups $upstream_http_remote_groups;
proxy_set_header X-Forwarded-User $user;
proxy_set_header X-Forwarded-Groups $groups;
error_page 401 =302 https://auth.example.com/?rd=$target_url;
```
