### ISSUE TITLE
Authelia and traefik

### ISSUE THREAD

**Issue by tcheronneau** [clems4ever/authelia#288] opened 2018-10-23 14:28 UTC
Hi,

Trying to setup authelia and traefik together and I've checked all previous issue to end with a configuration with the redirect param. 
But when I do : https://auth.mytld/api/verify?redirect=https://auth.mytld 
It's just returning a 401 : 
```
curl -vvv "authelia.auth.svc:8080/api/verify?redirect=https://auth.domain.tld"
*   Trying 10.32.0.48...
* TCP_NODELAY set
* Connected to authelia.auth.svc (10.32.0.48) port 8080 (#0)
> GET /api/verify?redirect=https://auth.domain.tld HTTP/1.1
> Host: authelia.auth.svc:8080
> User-Agent: curl/7.57.0
> Accept: */*
>
< HTTP/1.1 401 Unauthorized 
```

Do I need to put something special in authelia config ? 

Thanks.

**Comment by clems4ever** [comment] 2018-10-23 18:43
Hello @tcheronneau , this is a duplicate of #88. Please post in this thread instead. Thank you.

**Closed by clems4ever** 2018-10-23 18:43 UTC

**Comment by clems4ever** [comment] 2018-10-23 18:45
Also, I've never seen Traefik work with Authelia so far so please be more precise on the question(s) so that we can help you out more easily.

**Comment by tcheronneau** [comment] 2018-10-23 19:06
You’re saying in #88 that you solved from your side by adding the ?redirect=login.domain.tld but I tried directly in authelio with the redirect I get a 301 and no redirect (cf my curl). 
So how did you get the redirect working ?

Thanks.

**Comment by tcheronneau** [comment] 2018-10-23 19:28
But I’ve managed to « make it works » if I put the url to auth.domain.tld/loggedin you at least manage to validate the user is connected but not to check an acl unfortunatly.

**Comment by clems4ever** [comment] 2018-10-23 21:03
let's move to the open thread please.
