### ISSUE TITLE
Messages about mssing infrastructure

### ISSUE THREAD

**Issue by Rast1234** [clems4ever/authelia#78] opened 2017-09-08 16:52 UTC
Hello. Just installed authelia with docker-compose and got error like `TypeError: Cannot read property ‘auth’ of undefined \\ at Object.get (/usr/src/lib/AuthenticationSession.js:19:21)`. Spent some time understanding what's wrong until i realised that redis instance was in different network. Since authelia depends only on mongo, redis and openldap, maybe it's posible to add checks and human readable massages in case of similar exceptions to make it easier to set up? Like "mongo/redis/openldap server at <server_address> is unavailable, check your environment"

**Comment by clems4ever** [comment] 2017-09-09 08:28
Hello @Rast1234 , thank you for reporting. 
Have you directly used the docker-compose command to deploy or the provided script (given in the README)?

**Comment by Rast1234** [comment] 2017-09-09 08:36
I made custom docker-compose file myself. I checked that mongo/redis/ldap containers are available by logging in authelia container and pinging relevant hostnames.
Here is my `docker-compose.yml` if you are interested:
```
version: '2'
services:
  authelia:
    image: clems4ever/authelia
    container_name: authelia
    volumes:
      - /mnt/stuff/docker/authelia/config:/etc/authelia
      - /mnt/stuff/docker/authelia/data:/var/lib/authelia
    ports:
      - "42011:8080"
    links:
      - mongo:mongodb
      - openldap
    external_links:
      - redis
    network_mode: bridge

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - /mnt/stuff/docker/mongo:/data/db
    ports:
      - "27017:27017"
    network_mode: bridge

  openldap:
    image: dinkel/openldap
    container_name: openldap
    volumes:
      - /mnt/stuff/docker/openldap/conig:/etc/ldap
      - /mnt/stuff/docker/openldap/data:/var/lib/ldap
    environment:
      - SLAPD_PASSWORD=headshot
      - SLAPD_DOMAIN=rast.rocks
    network_mode: bridge

  phpldapadmin:
    image: dinkel/phpldapadmin
    container_name: phpldapadmin
    links:
      - openldap
    network_mode: bridge
    ports:
      - "8081:80"

```

**Comment by clems4ever** [comment] 2017-09-09 08:37
Can you please also post you configuration file?

**Comment by Rast1234** [comment] 2017-09-09 08:53
Sure, i based config on your template:

[config.yml](https://github.com/clems4ever/authelia/files/1289646/config.yml.txt)

**Comment by clems4ever** [comment] 2017-09-17 11:49
Hello @Rast1234 , sorry for the late reply. I see a typo in an openldap volume in the docker-compose.

    `/mnt/stuff/docker/openldap/conig:/etc/ldap`

Can it be your problem ?

**Comment by clems4ever** [comment] 2017-09-17 12:16
Hello @Rast1234 ,

I now reproduce the issue using the example environment. The error is appearing after I stop the redis container. So I guess there is something wrong with the docker-compose. There seems to be no link between redis and Authelia. Can you try to ping redis from the Authelia container to check?

Thanks,
Clément.

**Comment by clems4ever** [comment] 2017-09-17 12:17
In the meantime I'm providing a fix to see the error more clearly in the logs.

**Comment by clems4ever** [comment] 2017-09-22 19:12
Hello @Rast1234 , I've just merged #89 which will help you understand those problems more easily.
Please close the ticket when you've solved your issue.

**Comment by clems4ever** [comment] 2017-10-07 09:37
Hello @Rast1234 , any news?

**Comment by clems4ever** [comment] 2017-10-15 13:44
Please reopen the ticket if needed.

**Closed by clems4ever** 2017-10-15 13:44 UTC
Labels: bug, P4, question
