### ISSUE TITLE
Not redirected to the “already logged in” page

### ISSUE THREAD

**Issue by n4kre** [clems4ever/authelia#108] opened 2017-10-07 16:16 UTC
Hi,

Upon successful login, if I visit the login page again, I am prompted for my credentials: shouldn't the “already logged in” page be displayed instead?

Note: Not related to this issue, but the images within the green/redish notification frames are not properly displayed – it's not worth opening a new issue for it, I guess.

**Comment by clems4ever** [comment] 2017-10-07 16:26
Hello @n4kre, the behavior has changed since #98. Indeed, this PR gives a way to enable only basic authentication for certain domains.
The thing is, it makes no sense to say that a user is already logged in anymore since the user can now be logged in on subdomain 1 which supports basic auth and not logged in on subdomain 2 because it support 2-factor and it has not been validated yet. Make sense?

Please do create a ticket for the second issue. What is the behavior you're observing? Is it on mobile? Desktop? (can you please answer in the new ticket?)

**Comment by n4kre** [comment] 2017-10-07 16:49
I get your point.
Thing is it's a bit hard to know for the user whether it's logged in – and where – or not, and not very intuitive to log out – in case it is already logged in.
Maybe it would be a good idea to add a “Logout” button on the login page if the user is already logged in?

**Comment by clems4ever** [comment] 2017-10-07 17:00
Yes, it has always been a bit bad not to know wether you're logged in. 

Adding a "logout" button is a good idea but my problem is I can't tell whether I should display it or not because as I said previously there is no way for Authelia to tell if the user is logged in. Indeed, within the authentication portal, Authelia knows if the user has passed first factor and second factor but there is no way to tell what the user would like to access and thus if first factor is sufficient...
Any ideas?

**Comment by clems4ever** [comment] 2017-10-09 12:07
Hello @n4kre , #131 will fix this issue. The behavior will consequently be the following:
- If user has already validated first factor, when accessing the login page he is redirected to second factor page unless he tries to access a domain (based on redirect query parameter) protected by basic auth or no "redirect" is provided or he has already validated second factor.
- If user has already validated first and second factor, he is redirected to the target service (based on redirect query param) or to the "already logged in" page if no "redirect" is provided.

This new behavior is much better and straightforward indeed. I also added a logout link in the second factor page.

**Comment by n4kre** [comment] 2017-10-09 13:43
Sounds really good! Thank you @clems4ever

**Comment by clems4ever** [comment] 2017-10-09 21:28
Hello @n4kre , I merged #131. It implements what I described earlier.

**Closed by clems4ever** 2017-10-09 21:28 UTC
Labels: P2, question

**Comment by n4kre** [comment] 2017-10-09 22:01
Bonsoir Clément,

Encore merci pour tout ce que tu fais : ton projet Authelia est top !
Je suis content de pouvoir y “contribuer” légèrement, à ma manière – je ne suis pas développeur, mais la cybersécurité m’intéresse beaucoup.

À très vite sur Github – c’est d’ailleurs un peu artificiel de se parler anglais, mais la norme est ainsi –, ou à Atlanta, si tu es de passage dans la région avant la fin de l'année.

Bonne soirée,

Antoine Favre
Graduate student | ECE
Georgia Institute of Technology
+33 6 35 94 24 34<tel:+33635942434> | antoine.favre@gatech.edu<mailto:antoine.favre@gatech.edu>

On 9 Oct 2017, at 5:28 PM, Clément Michaud <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #108<https://github.com/clems4ever/authelia/issues/108>.

**Comment by n4kre** [comment] 2017-10-15 16:35
Hi @clems4ever,

This behavior seem to have a little bug.

**Setup**

`notverysensitive.example.com` is protected by single factor authentication – I have double checked – and `login.example.com` refers to Authelia.

**Test**

1. I log in at `https://login.example.com` – first factor only.
2. I visit `https://login.example.com/?redirect=https%3A%2F%2Fnotverysensitive.example.com%2F`.
3. I get redirected to `https://login.example.com/secondfactor?redirect=https%3A%2F%2Fnotverysensitive.example.com%2F` instead of `https://notverysensitive.example.com/`.

**Comment by n4kre** [comment] 2017-10-15 18:39
What's more, the “already logged in” page shouldn't be accessible from a non-logged-in user – e.g., should return an error 401.

**Comment by clems4ever** [comment] 2017-10-15 20:07
Issue with already logged in page is fixed but I cannot reproduce the single factor one.
